# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ('timestamp',),
                'verbose_name': 'log entry',
            },
        ),
    ]
